Funcionalidade filtro
gabrielligoski/CAMAAR pull request #17
Opened 2022-04-21 22:03 UTC by Thiago574

2022-04-22 23:48 UTC, FelipeFcosta approved these changes

2022-04-23 01:30 UTC, gabrielligoski requested changes
Precisa resolver conflitos antes de dar merge

2022-04-23 01:30 UTC, gabrielligoski commented on backend/db/seeds.rb
> +<<<<<<< HEAD
Creio que isso é conflito do github não resolvido que ficou para trás, as linhas de baixo comentadas com ==== , >>>> e <<<< também

2022-04-23 20:13 UTC, MrHolyveira approved these changes

2022-04-23 21:59 UTC, merged